<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="22" passed="16" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-02T16:23:17 ICT" name="SanPham" finished-at="2024-04-02T16:23:17 ICT" duration-ms="557">
    <groups>
    </groups>
    <test started-at="2024-04-02T16:23:17 ICT" name="SanPhamTest" finished-at="2024-04-02T16:23:17 ICT" duration-ms="557">
      <class name="Nhiem.SanPham.CapNhapTest">
        <test-method signature="TC_CAPNHAT_01()[pri:0, instance:Nhiem.SanPham.CapNhapTest@3c435123]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHAT_01" finished-at="2024-04-02T16:23:17 ICT" duration-ms="27" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHAT_01 -->
        <test-method signature="TC_CAPNHAT_02()[pri:0, instance:Nhiem.SanPham.CapNhapTest@3c435123]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHAT_02" finished-at="2024-04-02T16:23:17 ICT" duration-ms="20" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at Nhiem.SanPham.CapNhapTest.TC_CAPNHAT_02(CapNhapTest.java:42)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHAT_02 -->
        <test-method signature="TC_CAPNHAT_03()[pri:0, instance:Nhiem.SanPham.CapNhapTest@3c435123]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHAT_03" finished-at="2024-04-02T16:23:17 ICT" duration-ms="19" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at Nhiem.SanPham.CapNhapTest.TC_CAPNHAT_03(CapNhapTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHAT_03 -->
        <test-method signature="TC_CAPNHAT_04()[pri:0, instance:Nhiem.SanPham.CapNhapTest@3c435123]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHAT_04" finished-at="2024-04-02T16:23:17 ICT" duration-ms="25" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Nhiem.SanPham.CapNhapTest.TC_CAPNHAT_04(CapNhapTest.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHAT_04 -->
        <test-method signature="TC_CAPNHAT_05()[pri:0, instance:Nhiem.SanPham.CapNhapTest@3c435123]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHAT_05" finished-at="2024-04-02T16:23:17 ICT" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHAT_05 -->
      </class> <!-- Nhiem.SanPham.CapNhapTest -->
      <class name="Nhiem.SanPham.capNhapCTSPTest">
        <test-method signature="TC_CAPNHATCTSP_01()[pri:0, instance:Nhiem.SanPham.capNhapCTSPTest@726e5805]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHATCTSP_01" finished-at="2024-04-02T16:23:17 ICT" duration-ms="40" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHATCTSP_01 -->
        <test-method signature="TC_CAPNHATCTSP_02()[pri:0, instance:Nhiem.SanPham.capNhapCTSPTest@726e5805]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHATCTSP_02" finished-at="2024-04-02T16:23:17 ICT" duration-ms="26" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at Nhiem.SanPham.capNhapCTSPTest.TC_CAPNHATCTSP_02(capNhapCTSPTest.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHATCTSP_02 -->
        <test-method signature="TC_CAPNHATCTSP_03()[pri:0, instance:Nhiem.SanPham.capNhapCTSPTest@726e5805]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHATCTSP_03" finished-at="2024-04-02T16:23:17 ICT" duration-ms="34" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at Nhiem.SanPham.capNhapCTSPTest.TC_CAPNHATCTSP_03(capNhapCTSPTest.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHATCTSP_03 -->
        <test-method signature="TC_CAPNHATCTSP_04()[pri:0, instance:Nhiem.SanPham.capNhapCTSPTest@726e5805]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHATCTSP_04" finished-at="2024-04-02T16:23:17 ICT" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHATCTSP_04 -->
        <test-method signature="TC_CAPNHATCTSP_05()[pri:0, instance:Nhiem.SanPham.capNhapCTSPTest@726e5805]" started-at="2024-04-02T16:23:17 ICT" name="TC_CAPNHATCTSP_05" finished-at="2024-04-02T16:23:17 ICT" duration-ms="26" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_CAPNHATCTSP_05 -->
      </class> <!-- Nhiem.SanPham.capNhapCTSPTest -->
      <class name="Nhiem.SanPham.taoMaCTSPTest">
        <test-method signature="test_TC_TAOCTSP_01()[pri:0, instance:Nhiem.SanPham.taoMaCTSPTest@3e8f7922]" started-at="2024-04-02T16:23:17 ICT" name="test_TC_TAOCTSP_01" finished-at="2024-04-02T16:23:17 ICT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_TC_TAOCTSP_01 -->
        <test-method signature="test_TC_TAOCTSP_02()[pri:0, instance:Nhiem.SanPham.taoMaCTSPTest@3e8f7922]" started-at="2024-04-02T16:23:17 ICT" name="test_TC_TAOCTSP_02" finished-at="2024-04-02T16:23:17 ICT" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_TC_TAOCTSP_02 -->
        <test-method signature="test_TC_TAOCTSP_03()[pri:0, instance:Nhiem.SanPham.taoMaCTSPTest@3e8f7922]" started-at="2024-04-02T16:23:17 ICT" name="test_TC_TAOCTSP_03" finished-at="2024-04-02T16:23:17 ICT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_TC_TAOCTSP_03 -->
      </class> <!-- Nhiem.SanPham.taoMaCTSPTest -->
      <class name="Nhiem.SanPham.themCTSPTest">
        <test-method signature="TC_THEMCTSP_01()[pri:0, instance:Nhiem.SanPham.themCTSPTest@72e34f77]" started-at="2024-04-02T16:23:17 ICT" name="TC_THEMCTSP_01" finished-at="2024-04-02T16:23:17 ICT" duration-ms="34" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK__ChiTietS__1E4FCECD6073457E'. Cannot insert duplicate key in object 'dbo.ChiTietSanPham'. The duplicate key value is (SP003-1).]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK__ChiTietS__1E4FCECD6073457E'. Cannot insert duplicate key in object 'dbo.ChiTietSanPham'. The duplicate key value is (SP003-1).
at util.ConnectDB.executeUpdate(ConnectDB.java:144)
at util.ChiTietSanPhamDAO.insert(ChiTietSanPhamDAO.java:24)
at view.SanPham.ThemCTSP_Test(SanPham.java:330)
at Nhiem.SanPham.themCTSPTest.TC_THEMCTSP_01(themCTSPTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK__ChiTietS__1E4FCECD6073457E'. Cannot insert duplicate key in object 'dbo.ChiTietSanPham'. The duplicate key value is (SP003-1).
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:539)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4048)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:484)
at util.ConnectDB.executeUpdate(ConnectDB.java:141)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_THEMCTSP_01 -->
        <test-method signature="TC_THEMCTSP_02()[pri:0, instance:Nhiem.SanPham.themCTSPTest@72e34f77]" started-at="2024-04-02T16:23:17 ICT" name="TC_THEMCTSP_02" finished-at="2024-04-02T16:23:17 ICT" duration-ms="33" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_THEMCTSP_02 -->
        <test-method signature="TC_THEMCTSP_03()[pri:0, instance:Nhiem.SanPham.themCTSPTest@72e34f77]" started-at="2024-04-02T16:23:17 ICT" name="TC_THEMCTSP_03" finished-at="2024-04-02T16:23:17 ICT" duration-ms="43" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_THEMCTSP_03 -->
      </class> <!-- Nhiem.SanPham.themCTSPTest -->
      <class name="Nhiem.SanPham.themTest">
        <test-method signature="TC_THEM_01()[pri:0, instance:Nhiem.SanPham.themTest@3e2822]" started-at="2024-04-02T16:23:17 ICT" name="TC_THEM_01" finished-at="2024-04-02T16:23:17 ICT" duration-ms="43" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_THEM_01 -->
        <test-method signature="TC_THEM_02()[pri:0, instance:Nhiem.SanPham.themTest@3e2822]" started-at="2024-04-02T16:23:17 ICT" name="TC_THEM_02" finished-at="2024-04-02T16:23:17 ICT" duration-ms="36" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_THEM_02 -->
        <test-method signature="TC_THEM_03()[pri:0, instance:Nhiem.SanPham.themTest@3e2822]" started-at="2024-04-02T16:23:17 ICT" name="TC_THEM_03" finished-at="2024-04-02T16:23:17 ICT" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_THEM_03 -->
      </class> <!-- Nhiem.SanPham.themTest -->
      <class name="Nhiem.SanPham.taoMaSPTest">
        <test-method signature="C_TAOMASP_03()[pri:0, instance:Nhiem.SanPham.taoMaSPTest@7813cb11]" started-at="2024-04-02T16:23:17 ICT" name="C_TAOMASP_03" finished-at="2024-04-02T16:23:17 ICT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C_TAOMASP_03 -->
        <test-method signature="TC_TAOMASP_01()[pri:0, instance:Nhiem.SanPham.taoMaSPTest@7813cb11]" started-at="2024-04-02T16:23:17 ICT" name="TC_TAOMASP_01" finished-at="2024-04-02T16:23:17 ICT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_TAOMASP_01 -->
        <test-method signature="TC_TAOMASP_02()[pri:0, instance:Nhiem.SanPham.taoMaSPTest@7813cb11]" started-at="2024-04-02T16:23:17 ICT" name="TC_TAOMASP_02" finished-at="2024-04-02T16:23:17 ICT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_TAOMASP_02 -->
      </class> <!-- Nhiem.SanPham.taoMaSPTest -->
    </test> <!-- SanPhamTest -->
  </suite> <!-- SanPham -->
</testng-results>
