<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9I87QRH" failures="1" tests="4" name="Nhiem.Encode.EncodeTest" time="2.096" errors="0" timestamp="2024-04-01T12:01:31 ICT" skipped="0">
  <testcase classname="Nhiem.Encode.EncodeTest" name="TC_CHECK_02" time="0.665"/>
  <system-out/>
  <testcase classname="Nhiem.Encode.EncodeTest" name="TC_HASH_01" time="0.327"/>
  <system-out/>
  <testcase classname="Nhiem.Encode.EncodeTest" name="TC_CHECK_01" time="0.775"/>
  <system-out/>
  <testcase classname="Nhiem.Encode.EncodeTest" name="TC_HASH_02" time="0.329">
    <failure message="expected [null] but found [$2a$12$mF18HegBUM95Zw1Ur6L4Ue2vqB5VUL.tL.csznne7c3RXeOijU13S]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [null] but found [$2a$12$mF18HegBUM95Zw1Ur6L4Ue2vqB5VUL.tL.csznne7c3RXeOijU13S]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotSame(Assert.java:1033)
at org.testng.Assert.assertNull(Assert.java:965)
at org.testng.Assert.assertNull(Assert.java:953)
at Nhiem.Encode.EncodeTest.TC_HASH_02(EncodeTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_HASH_02 -->
  <system-out/>
</testsuite> <!-- Nhiem.Encode.EncodeTest -->
