<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9I87QRH" failures="3" tests="9" name="Nhiem.SanPham.themTest" time="1.070" errors="0" timestamp="2024-04-08T16:45:39 ICT" skipped="0">
  <testcase classname="Nhiem.SanPham.themTest" name="TC_THEMSP_07" time="0.091"/>
  <system-out/>
  <testcase classname="Nhiem.SanPham.themTest" name="TC_THEMSP_03" time="0.101"/>
  <system-out/>
  <testcase classname="Nhiem.SanPham.themTest" name="TC_THEMSP_02" time="0.108"/>
  <system-out/>
  <testcase classname="Nhiem.SanPham.themTest" name="TC_THEMSP_08" time="0.142">
    <failure message="expected [Lỗi mã KM không tồn tại] but found [java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of UNIQUE KEY constraint &#039;UQ__SanPham__8BBF4A1CBD3A9718&#039;. Cannot insert duplicate key in object &#039;dbo.SanPham&#039;. The duplicate key value is (000011).]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Lỗi mã KM không tồn tại] but found [java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of UNIQUE KEY constraint 'UQ__SanPham__8BBF4A1CBD3A9718'. Cannot insert duplicate key in object 'dbo.SanPham'. The duplicate key value is (000011).]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Nhiem.SanPham.themTest.TC_THEMSP_08(themTest.java:138)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_THEMSP_08 -->
  <system-out/>
  <testcase classname="Nhiem.SanPham.themTest" name="TC_THEMSP_04" time="0.128"/>
  <system-out/>
  <testcase classname="Nhiem.SanPham.themTest" name="TC_THEMSP_01" time="0.201">
    <failure message="expected [PASS] but found [java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of UNIQUE KEY constraint &#039;UQ__SanPham__8BBF4A1CBD3A9718&#039;. Cannot insert duplicate key in object &#039;dbo.SanPham&#039;. The duplicate key value is (100001).]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [PASS] but found [java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of UNIQUE KEY constraint 'UQ__SanPham__8BBF4A1CBD3A9718'. Cannot insert duplicate key in object 'dbo.SanPham'. The duplicate key value is (100001).]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Nhiem.SanPham.themTest.TC_THEMSP_01(themTest.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_THEMSP_01 -->
  <system-out/>
  <testcase classname="Nhiem.SanPham.themTest" name="TC_THEMSP_05" time="0.109"/>
  <system-out/>
  <testcase classname="Nhiem.SanPham.themTest" name="TC_THEMSP_06" time="0.093"/>
  <system-out/>
  <testcase classname="Nhiem.SanPham.themTest" name="TC_THEMSP_09" time="0.097">
    <failure message="expected [Lỗi mã LG không tồn tại] but found [java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of UNIQUE KEY constraint &#039;UQ__SanPham__8BBF4A1CBD3A9718&#039;. Cannot insert duplicate key in object &#039;dbo.SanPham&#039;. The duplicate key value is (000012).]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Lỗi mã LG không tồn tại] but found [java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of UNIQUE KEY constraint 'UQ__SanPham__8BBF4A1CBD3A9718'. Cannot insert duplicate key in object 'dbo.SanPham'. The duplicate key value is (000012).]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Nhiem.SanPham.themTest.TC_THEMSP_09(themTest.java:154)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_THEMSP_09 -->
  <system-out/>
</testsuite> <!-- Nhiem.SanPham.themTest -->
